language: node_js

node_js:
  - 'node'
  - 12
  - 10

install:
  - npm ci
  - lerna bootstrap

script:
  - nrun lint
  - nrun spell
  - nrun size
  - nrun test --coverage && cat coverage/lcov.info | coveralls
